export interface KanjiLevel {
  id: number;
  targetKanji: string;
  meaning: string;
  reading: string;
  options: string[];
}

export const ALL_LEVELS = {
  N5: [
    // --- TABIAT VA ELEMENTLAR ---
    { id: 1, targetKanji: "木", meaning: "Daraxt", reading: "ki", options: ["木", "本", "大", "末"] },
    { id: 2, targetKanji: "林", meaning: "Kichik o'rmon", reading: "hayashi", options: ["林", "森", "木", "村"] },
    { id: 3, targetKanji: "森", meaning: "O'rmon", reading: "mori", options: ["森", "林", "木", "品"] },
    { id: 4, targetKanji: "山", meaning: "Tog'", reading: "yama", options: ["山", "出", "凶", "仙"] },
    { id: 5, targetKanji: "川", meaning: "Daryo", reading: "kawa", options: ["川", "州", "三", "訓"] },
    { id: 6, targetKanji: "水", meaning: "Suv", reading: "mizu", options: ["水", "氷", "永", "求"] },
    { id: 7, targetKanji: "火", meaning: "Olov", reading: "hi", options: ["火", "灯", "人", "秋"] },
    { id: 8, targetKanji: "土", meaning: "Tuproq", reading: "tsuchi", options: ["土", "士", "上", "止"] },
    { id: 9, targetKanji: "天", meaning: "Osmon", reading: "ten", options: ["天", "夫", "矢", "失"] },
    { id: 10, targetKanji: "空", meaning: "Bo'shliq / Osmon", reading: "sora", options: ["空", "究", "突", "穴"] },
    { id: 11, targetKanji: "気", meaning: "Ruh / Havo", reading: "ki", options: ["気", "汽", "麦", "欠"] },
    { id: 12, targetKanji: "雨", meaning: "Yomg'ir", reading: "ame", options: ["雨", "両", "雪", "雲"] },
    // --- VAQT VA TAQVIM ---
    { id: 13, targetKanji: "日", meaning: "Quyosh / Kun", reading: "hi / nichi", options: ["日", "目", "田", "白"] },
    { id: 14, targetKanji: "月", meaning: "Oy", reading: "tsuki", options: ["月", "目", "用", "同"] },
    { id: 15, targetKanji: "年", meaning: "Yil", reading: "toshi", options: ["年", "午", "牛", "生"] },
    { id: 16, targetKanji: "今", meaning: "Hozir", reading: "ima", options: ["今", "合", "令", "会"] },
    { id: 17, targetKanji: "週", meaning: "Hafta", reading: "shuu", options: ["週", "週", "運", "道"] },
    { id: 18, targetKanji: "時", meaning: "Vaqt / Soat", reading: "toki / ji", options: ["時", "待", "持", "特"] },
    { id: 19, targetKanji: "分", meaning: "Daqiqa / Bo'lish", reading: "fun / bun", options: ["分", "公", "今", "介"] },
    { id: 20, targetKanji: "午", meaning: "Peshin", reading: "go", options: ["午", "牛", "年", "干"] },
    { id: 21, targetKanji: "毎", meaning: "Har safar", reading: "mai", options: ["毎", "母", "海", "毒"] },
    { id: 22, targetKanji: "間", meaning: "Oraliq / Davomida", reading: "aida", options: ["間", "問", "聞", "開"] },
    // --- SONLAR ---
    { id: 23, targetKanji: "一", meaning: "Bir", reading: "ichi", options: ["一", "二", "三", "十"] },
    { id: 24, targetKanji: "二", meaning: "Ikki", reading: "ni", options: ["二", "一", "三", "工"] },
    { id: 25, targetKanji: "三", meaning: "Uch", reading: "san", options: ["三", "二", "川", "𠂉"] },
    { id: 26, targetKanji: "四", meaning: "To'rt", reading: "yon", options: ["四", "西", "匹", "田"] },
    { id: 27, targetKanji: "五", meaning: "Besh", reading: "go", options: ["五", "互", "正", "丑"] },
    { id: 28, targetKanji: "六", meaning: "Olti", reading: "roku", options: ["六", "穴", "交", "公"] },
    { id: 29, targetKanji: "七", meaning: "Yetti", reading: "nana", options: ["七", "匕", "也", "切"] },
    { id: 30, targetKanji: "八", meaning: "Sakkiz", reading: "hachi", options: ["八", "人", "入", "ハ"] },
    { id: 31, targetKanji: "九", meaning: "To'qqiz", reading: "kyuu", options: ["九", "丸", "力", "刀"] },
    { id: 32, targetKanji: "十", meaning: "O'n", reading: "juu", options: ["十", "千", "土", "士"] },
    { id: 33, targetKanji: "百", meaning: "Yuz", reading: "hyaku", options: ["百", "白", "自", "面"] },
    { id: 34, targetKanji: "千", meaning: "Ming", reading: "sen", options: ["千", "十", "干", "于"] },
    { id: 35, targetKanji: "万", meaning: "O'n ming", reading: "man", options: ["万", "方", "力", "刀"] },
    { id: 36, targetKanji: "半", meaning: "Yarim", reading: "han", options: ["半", "平", "本", "干"] },
    { id: 37, targetKanji: "円", meaning: "Yen / Ayana", reading: "en", options: ["円", "内", "肉", "同"] },
    // --- ODAMLAR VA TANA ---
    { id: 38, targetKanji: "人", meaning: "Odam", reading: "hito", options: ["人", "入", "八", "個"] },
    { id: 39, targetKanji: "子", meaning: "Bola", reading: "ko", options: ["子", "了", "予", "学"] },
    { id: 40, targetKanji: "女", meaning: "Ayol", reading: "onna", options: ["女", "安", "好", "母"] },
    { id: 41, targetKanji: "男", meaning: "Erkak", reading: "otoko", options: ["男", "田", "力", "勇"] },
    { id: 42, targetKanji: "父", meaning: "Ota", reading: "chichi", options: ["父", "交", "文", "爷"] },
    { id: 43, targetKanji: "母", meaning: "Ona", reading: "haha", options: ["母", "毎", "海", "毋"] },
    { id: 44, targetKanji: "目", meaning: "Ko'z", reading: "me", options: ["目", "日", "自", "耳"] },
    { id: 45, targetKanji: "耳", meaning: "Quloq", reading: "mimi", options: ["耳", "目", "取", "聞"] },
    { id: 46, targetKanji: "口", meaning: "Og'iz", reading: "kuchi", options: ["口", "日", "回", "品"] },
    { id: 47, targetKanji: "手", meaning: "Qo'l", reading: "te", options: ["手", "毛", "千", "看"] },
    { id: 48, targetKanji: "足", meaning: "Oyoq", reading: "ashi", options: ["足", "是", "定", "走"] },
    // --- HARAKATLAR ---
    { id: 49, targetKanji: "行", meaning: "Bormoq", reading: "i-ku", options: ["行", "待", "街", "従"] },
    { id: 50, targetKanji: "来", meaning: "Kelmoq", reading: "ku-ru", options: ["来", "未", "末", "米"] },
    { id: 51, targetKanji: "食", meaning: "Yemoq", reading: "ta-beru", options: ["食", "飲", "良", "飯"] },
    { id: 52, targetKanji: "飲", meaning: "Ichmoq", reading: "no-mu", options: ["飲", "食", "飯", "飽"] },
    { id: 53, targetKanji: "見", meaning: "Ko'rmoq", reading: "mi-ru", options: ["見", "目", "貝", "規"] },
    { id: 54, targetKanji: "聞", meaning: "Eshitmoq", reading: "ki-ku", options: ["聞", "間", "問", "開"] },
    { id: 55, targetKanji: "読", meaning: "O'qimoq", reading: "yo-mu", options: ["読", "語", "話", "詩"] },
    { id: 56, targetKanji: "書", meaning: "Yozmoq", reading: "ka-ku", options: ["書", "昼", "画", "君"] },
    { id: 57, targetKanji: "話", meaning: "Gapirmoq", reading: "hana-su", options: ["話", "読", "語", "詰"] },
    { id: 58, targetKanji: "買", meaning: "Sotib olmoq", reading: "ka-u", options: ["買", "員", "賞", "売"] },
    { id: 59, targetKanji: "入", meaning: "Kirmoq", reading: "hai-ru", options: ["入", "人", "八", "込"] },
    { id: 60, targetKanji: "出", meaning: "Chiqmoq", reading: "de-ru", options: ["出", "山", "由", "曲"] },
    { id: 61, targetKanji: "立", meaning: "Turmoq", reading: "ta-tsu", options: ["立", "位", "音", "泣"] },
    { id: 62, targetKanji: "休", meaning: "Dam olmoq", reading: "yasu-mu", options: ["休", "体", "林", "保"] },
    { id: 63, targetKanji: "言", meaning: "Aytmoq", reading: "i-u", options: ["言", "信", "話", "計"] },
    { id: 64, targetKanji: "思", meaning: "O'ylamoq", reading: "omo-u", options: ["思", "恩", "心", "田"] },
    { id: 65, targetKanji: "語", meaning: "Gapirmoq / Til", reading: "kataru / go", options: ["語", "話", "読", "信"] },
    // --- YO'NALISH VA JOYLASHUV ---
    { id: 66, targetKanji: "上", meaning: "Tepa", reading: "ue", options: ["上", "下", "土", "止"] },
    { id: 67, targetKanji: "下", meaning: "Past", reading: "shita", options: ["下", "上", "不", "与"] },
    { id: 68, targetKanji: "左", meaning: "Chap", reading: "hidari", options: ["左", "右", "在", "友"] },
    { id: 69, targetKanji: "右", meaning: "O'ng", reading: "migi", options: ["右", "左", "石", "若"] },
    { id: 70, targetKanji: "中", meaning: "Ichida / Markaz", reading: "naka", options: ["中", "申", "串", "由"] },
    { id: 71, targetKanji: "外", meaning: "Tashqari", reading: "soto", options: ["外", "処", "名", "多"] },
    { id: 72, targetKanji: "前", meaning: "Oldin", reading: "mae", options: ["前", "煎", "箭", "月"] },
    { id: 73, targetKanji: "後", meaning: "Keyin / Orqa", reading: "ato", options: ["後", "待", "復", "役"] },
    { id: 74, targetKanji: "北", meaning: "Shimol", reading: "kita", options: ["北", "比", "此", "背"] },
    { id: 75, targetKanji: "南", meaning: "Janub", reading: "minami", options: ["南", "幸", "商", "楠"] },
    { id: 76, targetKanji: "東", meaning: "Sharq", reading: "higashi", options: ["東", "車", "練", "陳"] },
    { id: 77, targetKanji: "西", meaning: "G'arb", reading: "nishi", options: ["西", "四", "酉", "価"] },
    // --- JOYLAR ---
    { id: 78, targetKanji: "国", meaning: "Davlat", reading: "kuni", options: ["国", "回", "困", "園"] },
    { id: 79, targetKanji: "家", meaning: "Uy", reading: "ie", options: ["家", "安", "室", "容"] },
    { id: 80, targetKanji: "店", meaning: "Do'kon", reading: "mise", options: ["店", "広", "府", "座"] },
    { id: 81, targetKanji: "校", meaning: "Maktab binosi", reading: "kou", options: ["校", "交", "格", "稿"] },
    { id: 82, targetKanji: "電", meaning: "Elektr", reading: "den", options: ["電", "雷", "雨", "雪"] },
    { id: 83, targetKanji: "車", meaning: "Mashina", reading: "kuruma", options: ["車", "軍", "東", "軌"] },
    { id: 84, targetKanji: "道", meaning: "Yo'l", reading: "michi", options: ["道", "通", "運", "週"] },
    { id: 85, targetKanji: "駅", meaning: "Bekat", reading: "eki", options: ["駅", "駄", "験", "駐"] },
    // --- SIFATLAR ---
    { id: 86, targetKanji: "大", meaning: "Katta", reading: "oo-kii", options: ["大", "天", "太", "犬"] },
    { id: 87, targetKanji: "小", meaning: "Kichik", reading: "chii-sai", options: ["小", "少", "心", "水"] },
    { id: 88, targetKanji: "高", meaning: "Baland / Qimmat", reading: "taka-i", options: ["高", "亭", "京", "商"] },
    { id: 89, targetKanji: "安", meaning: "Arzon / Tinch", reading: "yasu-i", options: ["安", "女", "字", "家"] },
    { id: 90, targetKanji: "新", meaning: "Yangi", reading: "atara-shii", options: ["新", "親", "薪", "研"] },
    { id: 91, targetKanji: "古", meaning: "Eski", reading: "furu-i", options: ["古", "右", "石", "占"] },
    { id: 92, targetKanji: "多", meaning: "Ko'p", reading: "oo-i", options: ["多", "名", "外", "夕"] },
    { id: 93, targetKanji: "少", meaning: "Kam", reading: "suku-nai", options: ["少", "小", "歩", "省"] },
    { id: 94, targetKanji: "長", meaning: "Uzun", reading: "naga-i", options: ["長", "張", "帳", "髪"] },
    { id: 95, targetKanji: "白", meaning: "Oq", reading: "shiro", options: ["白", "百", "自", "面"] },
    // --- BOSHQA MUHIMLAR ---
    { id: 96, targetKanji: "友", meaning: "Do'st", reading: "tomo", options: ["友", "有", "左", "右"] },
    { id: 97, targetKanji: "名", meaning: "Ism", reading: "na", options: ["名", "各", "多", "外"] },
    { id: 98, targetKanji: "何", meaning: "Nima", reading: "nani", options: ["何", "向", "荷", "河"] },
    { id: 99, targetKanji: "先", meaning: "Avvalgi / Ustoz", reading: "saki", options: ["先", "失", "光", "洗"] },
    { id: 100, targetKanji: "生", meaning: "Hayot / Talaba", reading: "sei", options: ["生", "牛", "午", "年"] },
    { id: 101, targetKanji: "学", meaning: "O'qish", reading: "gaku", options: ["学", "字", "子", "校"] },
    { id: 102, targetKanji: "本", meaning: "Kitob", reading: "hon", options: ["本", "木", "体", "末"] },
    { id: 103, targetKanji: "金", meaning: "Oltin / Pul", reading: "kane", options: ["金", "全", "銀", "企"] },
    { id: 104, targetKanji: "曜", meaning: "Hafta kuni", reading: "you", options: ["曜", "濯", "躍", "日"] },
    { id: 105, targetKanji: "魚", meaning: "Baliq", reading: "sakana", options: ["魚", "鳥", "馬", "角"] },
    { id: 106, targetKanji: "肉", meaning: "Go'sht", reading: "niku", options: ["肉", "内", "月", "同"] },
    { id: 107, targetKanji: "犬", meaning: "It", reading: "inu", options: ["犬", "大", "太", "天"] },
    { id: 108, targetKanji: "門", meaning: "Darvoza", reading: "mon", options: ["門", "間", "問", "聞"] },
    { id: 109, targetKanji: "社", meaning: "Kompaniya", reading: "sha", options: ["社", "神", "礼", "ネ"] },
    { id: 110, targetKanji: "外", meaning: "Chet (el)", reading: "gai", options: ["外", "多", "夕", "名"] }
  ],
  
  N4: [
    // --- OILA VA ODAMLAR ---
    { id: 1, targetKanji: "兄", meaning: "Aka", reading: "ani", options: ["兄", "只", "足", "党"] },
    { id: 2, targetKanji: "姉", meaning: "Opa", reading: "ane", options: ["姉", "妹", "女", "始"] },
    { id: 3, targetKanji: "弟", meaning: "Uka", reading: "otouto", options: ["弟", "第", "市", "万"] },
    { id: 4, targetKanji: "妹", meaning: "Singil", reading: "imouto", options: ["妹", "姉", "味", "姓"] },
    { id: 5, targetKanji: "族", meaning: "Oila", reading: "zoku", options: ["族", "旅", "旗", "遊"] },
    { id: 6, targetKanji: "親", meaning: "Ota-ona / Yaqin", reading: "oya / shin", options: ["親", "新", "視", "木"] },
    { id: 7, targetKanji: "妻", meaning: "Xotin", reading: "tsuma", options: ["妻", "女", "安", "毒"] },
    { id: 8, targetKanji: "夫", meaning: "Er", reading: "otto", options: ["夫", "天", "失", "矢"] },
    { id: 9, targetKanji: "主", meaning: "Xo'jayin", reading: "nushi / shu", options: ["主", "王", "玉", "生"] },
    { id: 10, targetKanji: "奥", meaning: "Ichki / Xotin (boshqaning)", reading: "oku", options: ["奥", "戻", "笑", "臭"] },
    { id: 11, targetKanji: "私", meaning: "Men", reading: "watashi", options: ["私", "秋", "和", "科"] },
    { id: 12, targetKanji: "員", meaning: "A'zo / Xodim", reading: "in", options: ["員", "買", "見", "貝"] },
    { id: 13, targetKanji: "者", meaning: "Shaxs", reading: "mono / sha", options: ["者", "考", "老", "著"] },
    { id: 14, targetKanji: "医", meaning: "Tibbiyot", reading: "i", options: ["医", "区", "匹", "凶"] },
    { id: 15, targetKanji: "業", meaning: "Kasb", reading: "gyou", options: ["業", "薬", "楽", "乗"] },
    
    // --- HARAKATLAR VA FE'LLAR (Murakkab) ---
    { id: 16, targetKanji: "勉", meaning: "Tirishmoq", reading: "ben", options: ["勉", "強", "免", "晩"] },
    { id: 17, targetKanji: "強", meaning: "Kuchli / Majburlamoq", reading: "tsuyo-i / kyou", options: ["強", "弱", "弓", "弘"] },
    { id: 18, targetKanji: "答", meaning: "Javob bermoq", reading: "kota-eru", options: ["答", "合", "等", "管"] },
    { id: 19, targetKanji: "問", meaning: "Savol bermoq", reading: "to-u", options: ["問", "間", "聞", "開"] },
    { id: 20, targetKanji: "試", meaning: "Sinamoq", reading: "kokoro-miru", options: ["試", "式", "言", "誠"] },
    { id: 21, targetKanji: "験", meaning: "Imtihon / Tajriba", reading: "ken", options: ["験", "険", "馬", "駅"] },
    { id: 22, targetKanji: "歌", meaning: "Qo'shiq kuylamoq", reading: "uta", options: ["歌", "歓", "飲", "吹"] },
    { id: 23, targetKanji: "借", meaning: "Qarzga olmoq", reading: "ka-riru", options: ["借", "貸", "昔", "散"] },
    { id: 24, targetKanji: "貸", meaning: "Qarzga bermoq", reading: "ka-su", options: ["貸", "借", "代", "貨"] },
    { id: 25, targetKanji: "送", meaning: "Jo'natmoq", reading: "oku-ru", options: ["送", "道", "速", "近"] },
    { id: 26, targetKanji: "切", meaning: "Kesmoq", reading: "ki-ru", options: ["切", "七", "分", "刀"] },
    { id: 27, targetKanji: "洗", meaning: "Yuvmoq", reading: "ara-u", options: ["洗", "先", "波", "注"] },
    { id: 28, targetKanji: "急", meaning: "Shoshilmoq", reading: "iso-gu", options: ["急", "心", "思", "息"] },
    { id: 29, targetKanji: "開", meaning: "Ochmoq", reading: "a-ku", options: ["開", "閉", "間", "門"] },
    { id: 30, targetKanji: "閉", meaning: "Yopmoq", reading: "shi-meru", options: ["閉", "開", "間", "問"] },
    { id: 31, targetKanji: "押", meaning: "Bosmoq", reading: "o-su", options: ["押", "指", "持", "抜"] },
    { id: 32, targetKanji: "引", meaning: "Tortmoq", reading: "hi-ku", options: ["引", "弓", "張", "弘"] },
    { id: 33, targetKanji: "建", meaning: "Qurmoq", reading: "ta-teru", options: ["建", "健", "律", "書"] },
    { id: 34, targetKanji: "着", meaning: "Kiymoq / Yetib bormoq", reading: "ki-ru / tsu-ku", options: ["着", "看", "差", "表"] },
    { id: 35, targetKanji: "脱", meaning: "Yechmoq", reading: "nu-gu", options: ["脱", "説", "悦", "肉"] },
    { id: 36, targetKanji: "起", meaning: "Uyg'onmoq", reading: "o-kiru", options: ["起", "走", "超", "越"] },
    { id: 37, targetKanji: "寝", meaning: "Uxlamoq", reading: "ne-ru", options: ["寝", "寒", "宿", "覚"] },
    { id: 38, targetKanji: "働", meaning: "Ishlamoq", reading: "hatara-ku", options: ["働", "動", "重", "力"] },
    { id: 39, targetKanji: "止", meaning: "To'xtamoq", reading: "to-maru", options: ["止", "上", "正", "歩"] },
    { id: 40, targetKanji: "歩", meaning: "Yurmoq", reading: "aru-ku", options: ["歩", "走", "止", "少"] },
    { id: 41, targetKanji: "走", meaning: "Yugurmoq", reading: "hashi-ru", options: ["走", "起", "歩", "足"] },
    { id: 42, targetKanji: "待", meaning: "Kutmoq", reading: "ma-tsu", options: ["待", "持", "時", "特"] },
    { id: 43, targetKanji: "立", meaning: "Turmoq", reading: "ta-tsu", options: ["立", "位", "音", "泣"] },
    { id: 44, targetKanji: "座", meaning: "O'tirmoq", reading: "suwa-ru", options: ["座", "店", "広", "庭"] },
    { id: 45, targetKanji: "乗", meaning: "Minmoq", reading: "no-ru", options: ["乗", "降", "重", "飛"] },
    { id: 46, targetKanji: "降", meaning: "Tushmoq / Yog'moq", reading: "o-riru", options: ["降", "乗", "陣", "隆"] },
    { id: 47, targetKanji: "帰", meaning: "Qaytmoq", reading: "kae-ru", options: ["帰", "掃", "婦", "師"] },
    { id: 48, targetKanji: "死", meaning: "O'lmoq", reading: "shi-nu", options: ["死", "列", "老", "悲"] },
    { id: 49, targetKanji: "知", meaning: "Bilmoq", reading: "shi-ru", options: ["知", "和", "智", "口"] },
    { id: 50, targetKanji: "覚", meaning: "Eslab qolmoq", reading: "obo-eru", options: ["覚", "寝", "見", "学"] },
    { id: 51, targetKanji: "忘", meaning: "Unutmoq", reading: "wasu-reru", options: ["忘", "忙", "思", "心"] },
    { id: 52, targetKanji: "考", meaning: "O'ylamoq", reading: "kanga-eru", options: ["考", "老", "者", "孝"] },
    { id: 53, targetKanji: "決", meaning: "Qaror qilmoq", reading: "ki-meru", options: ["決", "次", "快", "冷"] },
    { id: 54, targetKanji: "定", meaning: "Belgilamoq", reading: "sada-meru", options: ["定", "足", "走", "正"] },
    { id: 55, targetKanji: "信", meaning: "Ishonmoq", reading: "shin", options: ["信", "言", "話", "伝"] },
    { id: 56, targetKanji: "記", meaning: "Yozib olmoq", reading: "ki", options: ["記", "起", "紀", "言"] },
    { id: 57, targetKanji: "説", meaning: "Tushuntirmoq", reading: "setsu", options: ["説", "読", "話", "脱"] },
    { id: 58, targetKanji: "売", meaning: "Sotmoq", reading: "u-ru", options: ["売", "買", "読", "続"] },
    { id: 59, targetKanji: "返", meaning: "Qaytarmoq", reading: "kae-su", options: ["返", "反", "坂", "板"] },
    { id: 60, targetKanji: "払", meaning: "To'lamoq", reading: "hara-u", options: ["払", "打", "広", "仏"] },
    { id: 61, targetKanji: "使", meaning: "Ishlatmoq", reading: "tsuka-u", options: ["使", "便", "信", "作"] },
    { id: 62, targetKanji: "始", meaning: "Boshlamoq", reading: "haji-meru", options: ["始", "治", "台", "女"] },
    { id: 63, targetKanji: "終", meaning: "Tugatmoq", reading: "owa-ru", options: ["終", "糸", "冬", "絵"] },
    { id: 64, targetKanji: "運", meaning: "Omad / Tashimoq", reading: "un", options: ["運", "連", "道", "週"] },
    { id: 65, targetKanji: "転", meaning: "Aylanmoq", reading: "koro-bu / ten", options: ["転", "車", "伝", "動"] },
    { id: 66, targetKanji: "作", meaning: "Yaratmoq", reading: "tsuku-ru", options: ["作", "昨", "使", "代"] },
    { id: 67, targetKanji: "用", meaning: "Ishlatmoq / Vazifa", reading: "you", options: ["用", "月", "角", "周"] },

    // --- JOYLAR VA BINOLAR ---
    { id: 68, targetKanji: "堂", meaning: "Zal / Xona", reading: "dou", options: ["堂", "常", "当", "室"] },
    { id: 69, targetKanji: "院", meaning: "Muassasa", reading: "in", options: ["院", "完", "館", "病"] },
    { id: 70, targetKanji: "病", meaning: "Kasallik", reading: "byou", options: ["病", "痛", "疲", "病院"] },
    { id: 71, targetKanji: "薬", meaning: "Dori", reading: "kusuri", options: ["薬", "楽", "業", "葉"] },
    { id: 72, targetKanji: "局", meaning: "Byuro / Bo'lim", reading: "kyoku", options: ["局", "屋", "居", "句"] },
    { id: 73, targetKanji: "線", meaning: "Chiziq / Liniya", reading: "sen", options: ["線", "糸", "緑", "練"] },
    { id: 74, targetKanji: "鉄", meaning: "Temir", reading: "tetsu", options: ["鉄", "金", "失", "銀"] },
    { id: 75, targetKanji: "宿", meaning: "Mehmonxona", reading: "yado / shuku", options: ["宿", "寝", "客", "家"] },
    { id: 76, targetKanji: "室", meaning: "Xona", reading: "shitsu", options: ["室", "屋", "空", "家"] },
    { id: 77, targetKanji: "館", meaning: "Bino / Saroy", reading: "kan", options: ["館", "飲", "飯", "官"] },
    { id: 78, targetKanji: "園", meaning: "Bog'", reading: "en", options: ["園", "遠", "国", "回"] },
    { id: 79, targetKanji: "所", meaning: "Joy", reading: "tokoro", options: ["所", "局", "場", "戸"] },
    { id: 80, targetKanji: "場", meaning: "Maydon", reading: "ba", options: ["場", "湯", "陽", "所"] },
    { id: 81, targetKanji: "屋", meaning: "Tom / Do'kon", reading: "ya", options: ["屋", "室", "居", "昼"] },
    { id: 82, targetKanji: "寺", meaning: "Ibodatxona", reading: "tera", options: ["寺", "待", "時", "持"] },
    { id: 83, targetKanji: "神", meaning: "Xudo", reading: "kami", options: ["神", "社", "申", "袖"] },
    { id: 84, targetKanji: "町", meaning: "Shahar", reading: "machi", options: ["町", "村", "田", "市"] },
    { id: 85, targetKanji: "村", meaning: "Qishloq", reading: "mura", options: ["村", "林", "町", "木"] },
    { id: 86, targetKanji: "市", meaning: "Shahar / Bozor", reading: "shi", options: ["市", "民", "町", "区"] },
    { id: 87, targetKanji: "区", meaning: "Tuman", reading: "ku", options: ["区", "医", "匹", "凶"] },
    { id: 88, targetKanji: "県", meaning: "Prefektura", reading: "ken", options: ["県", "見", "糸", "貝"] },
    { id: 89, targetKanji: "都", meaning: "Poytaxt", reading: "to", options: ["都", "者", "部", "郡"] },
    { id: 90, targetKanji: "京", meaning: "Poytaxt", reading: "kyou", options: ["京", "高", "涼", "景"] },
    { id: 91, targetKanji: "世", meaning: "Dunyo / Avlod", reading: "se", options: ["世", "界", "出", "甘"] },
    { id: 92, targetKanji: "界", meaning: "Chegara / Olam", reading: "kai", options: ["界", "世", "田", "男"] },
    { id: 93, targetKanji: "港", meaning: "Port", reading: "minato", options: ["港", "海", "波", "水"] },

    // --- VAQT VA TABIAT ---
    { id: 94, targetKanji: "夏", meaning: "Yoz", reading: "natsu", options: ["夏", "冬", "春", "秋"] },
    { id: 95, targetKanji: "冬", meaning: "Qish", reading: "fuyu", options: ["冬", "夏", "冷", "寒"] },
    { id: 96, targetKanji: "春", meaning: "Bahor", reading: "haru", options: ["春", "秋", "昼", "茶"] },
    { id: 97, targetKanji: "秋", meaning: "Kuz", reading: "aki", options: ["秋", "火", "私", "春"] },
    { id: 98, targetKanji: "朝", meaning: "Ertalab", reading: "asa", options: ["朝", "昼", "夕", "月"] },
    { id: 99, targetKanji: "昼", meaning: "Kunduzi", reading: "hiru", options: ["昼", "朝", "尽", "尺"] },
    { id: 100, targetKanji: "夕", meaning: "Kechqurun", reading: "yuu", options: ["夕", "多", "名", "外"] },
    { id: 101, targetKanji: "夜", meaning: "Tun", reading: "yoru", options: ["夜", "晩", "液", "夕"] },
    { id: 102, targetKanji: "晩", meaning: "Kech / Tun", reading: "ban", options: ["晩", "免", "勉", "夜"] },
    { id: 103, targetKanji: "正", meaning: "To'g'ri", reading: "tada-shii", options: ["正", "止", "上", "王"] },
    { id: 104, targetKanji: "早", meaning: "Erta", reading: "haya-i", options: ["早", "草", "日", "遅"] },
    { id: 105, targetKanji: "遅", meaning: "Kech", reading: "oso-i", options: ["遅", "速", "近", "遠"] },
    { id: 106, targetKanji: "風", meaning: "Shamol", reading: "kaze", options: ["風", "風呂", "嵐", "雨"] },
    { id: 107, targetKanji: "雪", meaning: "Qor", reading: "yuki", options: ["雪", "雨", "雲", "雷"] },
    { id: 108, targetKanji: "雲", meaning: "Bulut", reading: "kumo", options: ["雲", "雪", "雨", "電"] },
    { id: 109, targetKanji: "波", meaning: "To'lqin", reading: "nami", options: ["波", "彼", "皮", "海"] },
    { id: 110, targetKanji: "海", meaning: "Dengiz", reading: "umi", options: ["海", "毎", "洋", "波"] },
    { id: 111, targetKanji: "池", meaning: "Hovuz", reading: "ike", options: ["池", "地", "他", "水"] },
    { id: 112, targetKanji: "陸", meaning: "Quruqlik", reading: "riku", options: ["陸", "海", "降", "空"] },
    { id: 113, targetKanji: "洋", meaning: "Okean / G'arb", reading: "you", options: ["洋", "様", "海", "羊"] },
    { id: 114, targetKanji: "島", meaning: "Orol", reading: "shima", options: ["島", "鳥", "山", "半島"] },
    { id: 115, targetKanji: "庭", meaning: "Hovli", reading: "niwa", options: ["庭", "店", "広", "座"] },
    { id: 116, targetKanji: "葉", meaning: "Barg", reading: "ha", options: ["葉", "草", "花", "薬"] },
    { id: 117, targetKanji: "花", meaning: "Gul", reading: "hana", options: ["花", "草", "化", "茶"] },
    { id: 118, targetKanji: "牛", meaning: "Sigir", reading: "ushi", options: ["牛", "午", "年", "生"] },
    { id: 119, targetKanji: "鳥", meaning: "Qush", reading: "tori", options: ["鳥", "島", "馬", "魚"] },
    { id: 120, targetKanji: "馬", meaning: "Ot", reading: "uma", options: ["馬", "鳥", "駅", "験"] },

    // --- SIFATLAR VA XUSUSIYATLAR ---
    { id: 121, targetKanji: "暑", meaning: "Issiq (havo)", reading: "atsu-i", options: ["暑", "熱", "寒", "者"] },
    { id: 122, targetKanji: "寒", meaning: "Sovuq (havo)", reading: "samu-i", options: ["寒", "暑", "冷", "寝"] },
    { id: 123, targetKanji: "温", meaning: "Iliq", reading: "atata-kai", options: ["温", "熱", "冷", "湿"] },
    { id: 124, targetKanji: "冷", meaning: "Sovuq (narsa)", reading: "tsume-tai", options: ["冷", "寒", "令", "決"] },
    { id: 125, targetKanji: "低", meaning: "Past", reading: "hiku-i", options: ["低", "底", "高", "氏"] },
    { id: 126, targetKanji: "暗", meaning: "Qorong'i", reading: "kura-i", options: ["暗", "明", "音", "黒"] },
    { id: 127, targetKanji: "明", meaning: "Yorug'", reading: "aka-rui", options: ["明", "暗", "日", "月"] },
    { id: 128, targetKanji: "悪", meaning: "Yomon", reading: "waru-i", options: ["悪", "良", "心", "思"] },
    { id: 129, targetKanji: "良", meaning: "Yaxshi", reading: "yo-i", options: ["良", "食", "悪", "娘"] },
    { id: 130, targetKanji: "青", meaning: "Ko'k", reading: "ao", options: ["青", "晴", "静", "赤"] },
    { id: 131, targetKanji: "赤", meaning: "Qizil", reading: "aka", options: ["赤", "青", "黒", "色"] },
    { id: 132, targetKanji: "黒", meaning: "Qora", reading: "kuro", options: ["黒", "白", "里", "赤"] },
    { id: 133, targetKanji: "黄", meaning: "Sariq", reading: "kiiro", options: ["黄", "横", "広", "共"] },
    { id: 134, targetKanji: "茶", meaning: "Choy / Jigarrang", reading: "cha", options: ["茶", "草", "花", "答"] },
    { id: 135, targetKanji: "色", meaning: "Rang", reading: "iro", options: ["色", "危", "角", "免"] },
    { id: 136, targetKanji: "重", meaning: "Og'ir", reading: "omo-i", options: ["重", "軽", "動", "働"] },
    { id: 137, targetKanji: "軽", meaning: "Yengil", reading: "karu-i", options: ["軽", "経", "車", "重"] },
    { id: 138, targetKanji: "広", meaning: "Keng", reading: "hiro-i", options: ["広", "店", "座", "黄"] },
    { id: 139, targetKanji: "短", meaning: "Qisqa", reading: "mijika-i", options: ["短", "知", "矢", "長"] },
    { id: 140, targetKanji: "痛", meaning: "Og'riq", reading: "ita-i", options: ["痛", "病", "疲", "通"] },
    { id: 141, targetKanji: "忙", meaning: "Band", reading: "isoga-shii", options: ["忙", "忘", "心", "亡"] },
    { id: 142, targetKanji: "特", meaning: "Maxsus", reading: "toku", options: ["特", "待", "持", "時"] },
    { id: 143, targetKanji: "別", meaning: "Boshqa / Ajralish", reading: "betsu", options: ["別", "分", "刀", "列"] },
    { id: 144, targetKanji: "有", meaning: "Bor", reading: "yuu", options: ["有", "右", "友", "無"] },
    { id: 145, targetKanji: "便", meaning: "Qulay / Pochta", reading: "ben", options: ["便", "使", "更", "硬"] },
    { id: 146, targetKanji: "利", meaning: "Foyda", reading: "ri", options: ["利", "和", "私", "乗"] },
    { id: 147, targetKanji: "不", meaning: "Inkor (Non-)", reading: "fu", options: ["不", "下", "木", "本"] },

    // --- NARSALAR VA TUSHUNCHALAR ---
    { id: 148, targetKanji: "音", meaning: "Ovoz", reading: "oto", options: ["音", "暗", "意", "立"] },
    { id: 149, targetKanji: "楽", meaning: "Qiziqarli / Musiqa", reading: "tano-shii", options: ["楽", "薬", "業", "乗"] },
    { id: 150, targetKanji: "物", meaning: "Narsa", reading: "mono", options: ["物", "牛", "特", "者"] },
    { id: 151, targetKanji: "心", meaning: "Yurak / Qalb", reading: "kokoro", options: ["心", "必", "思", "急"] },
    { id: 152, targetKanji: "顔", meaning: "Yuz / Aft", reading: "kao", options: ["顔", "頭", "題", "願"] },
    { id: 153, targetKanji: "首", meaning: "Bo'yin", reading: "kubi", options: ["首", "道", "頭", "自"] },
    { id: 154, targetKanji: "服", meaning: "Kiyim", reading: "fuku", options: ["服", "報", "皮", "波"] },
    { id: 155, targetKanji: "紙", meaning: "Qog'oz", reading: "kami", options: ["紙", "氏", "糸", "線"] },
    { id: 156, targetKanji: "形", meaning: "Shakl", reading: "katachi", options: ["形", "人形", "影", "髪"] },
    { id: 157, targetKanji: "品", meaning: "Mahsulot", reading: "shina", options: ["品", "口", "区", "器"] },
    { id: 158, targetKanji: "代", meaning: "O'rniga / To'lov", reading: "dai", options: ["代", "貸", "化", "伐"] },
    { id: 159, targetKanji: "産", meaning: "Ishlab chiqarish", reading: "san", options: ["産", "生", "立", "文"] },
    { id: 160, targetKanji: "工", meaning: "Sanoat", reading: "kou", options: ["工", "二", "エ", "土"] },
    { id: 161, targetKanji: "事", meaning: "Ish / Voqea", reading: "koto", options: ["事", "書", "争", "言"] },
    { id: 162, targetKanji: "図", meaning: "Xarita / Chizma", reading: "zu", options: ["図", "国", "回", "園"] },
    { id: 163, targetKanji: "声", meaning: "Ovoz (odamniki)", reading: "koe", options: ["声", "音", "売", "麦"] },
    { id: 164, targetKanji: "理", meaning: "Mantiq / Sabab", reading: "ri", options: ["理", "王", "里", "黒"] },
    { id: 165, targetKanji: "料", meaning: "To'lov / Material", reading: "ryou", options: ["料", "科", "米", "半"] },
    { id: 166, targetKanji: "飯", meaning: "Ovqat / Guruch", reading: "meshi", options: ["飯", "食", "飲", "館"] },
    { id: 167, targetKanji: "味", meaning: "Ta'm", reading: "aji", options: ["味", "妹", "口", "未"] },
    { id: 168, targetKanji: "注", meaning: "Quyish / Diqqat", reading: "chuu", options: ["注", "主", "水", "洗"] },
    { id: 169, targetKanji: "意", meaning: "Ma'no", reading: "i", options: ["意", "音", "心", "思"] },
    { id: 170, targetKanji: "化", meaning: "Aylanmoq (-zatsiya)", reading: "ka", options: ["化", "花", "代", "七"] },
    { id: 171, targetKanji: "字", meaning: "Harf", reading: "ji", options: ["字", "学", "子", "安"] },
    { id: 172, targetKanji: "文", meaning: "Matn / Gap", reading: "bun", options: ["文", "父", "交", "字"] },
    
    // --- QO'SHIMCHA MUHIM KANJILAR (Kundalik hayot uchun) ---
    { id: 173, targetKanji: "通", meaning: "O'tmoq / Qatnamoq", reading: "kayo-u", options: ["通", "道", "週", "痛"] },
    { id: 174, targetKanji: "動", meaning: "Harakatlanmoq", reading: "ugo-ku", options: ["動", "働", "重", "力"] },
    { id: 175, targetKanji: "建", meaning: "Bino", reading: "tate", options: ["建", "健", "書", "律"] },
    { id: 176, targetKanji: "計", meaning: "O'lchamoq / Reja", reading: "kei", options: ["計", "言", "針", "汁"] },
    { id: 177, targetKanji: "台", meaning: "Stend / Mashina (hisob so'zi)", reading: "dai", options: ["台", "始", "治", "口"] },
    { id: 178, targetKanji: "銀", meaning: "Kumush", reading: "gin", options: ["銀", "金", "鉄", "根"] },
    { id: 179, targetKanji: "頭", meaning: "Bosh", reading: "atama", options: ["頭", "顔", "願", "首"] },
    { id: 180, targetKanji: "糸", meaning: "Ip", reading: "ito", options: ["糸", "紙", "線", "終"] },
    { id: 181, targetKanji: "冬", meaning: "Qish", reading: "fuyu", options: ["冬", "夏", "寒", "麦"] },
    { id: 182, targetKanji: "昔", meaning: "O'tmish", reading: "mukashi", options: ["昔", "借", "黄", "散"] },
    { id: 183, targetKanji: "体", meaning: "Tana", reading: "karada", options: ["体", "休", "本", "木"] },
    { id: 184, targetKanji: "集", meaning: "To'plamoq", reading: "atsu-meru", options: ["集", "進", "隹", "木"] },
    { id: 185, targetKanji: "進", meaning: "Olg'a yurmoq", reading: "susu-mu", options: ["進", "集", "道", "近"] },
    { id: 186, targetKanji: "近", meaning: "Yaqin", reading: "chika-i", options: ["近", "遠", "送", "遅"] },
    { id: 187, targetKanji: "遠", meaning: "Uzoq", reading: "too-i", options: ["遠", "近", "園", "達"] },
    { id: 188, targetKanji: "酒", meaning: "Spirtli ichimlik", reading: "sake", options: ["酒", "酉", "西", "配"] },
    { id: 189, targetKanji: "配", meaning: "Tarqatmoq", reading: "hai", options: ["配", "酒", "己", "起"] },
    { id: 190, targetKanji: "以", meaning: "...dan (vaqt/joy)", reading: "i", options: ["以", "似", "人", "外"] },
    { id: 191, targetKanji: "内", meaning: "Ichki", reading: "uchi", options: ["内", "肉", "円", "入"] },
    { id: 192, targetKanji: "同", meaning: "Bir xil", reading: "ona-ji", options: ["同", "向", "月", "円"] },
    { id: 193, targetKanji: "向", meaning: "Yuzlanmoq / Tomon", reading: "mu-kau", options: ["向", "同", "何", "問"] },
    { id: 194, targetKanji: "真", meaning: "Haqiqat", reading: "shin", options: ["真", "直", "具", "写真"] },
    { id: 195, targetKanji: "野", meaning: "Dala", reading: "no", options: ["野", "里", "里", "野球"] },
    { id: 196, targetKanji: "菜", meaning: "Sabzavot", reading: "sai", options: ["菜", "葉", "草", "花"] },
    { id: 197, targetKanji: "洋", meaning: "G'arbiy", reading: "you", options: ["洋", "海", "羊", "様"] },
    { id: 198, targetKanji: "様", meaning: "Janob / Holat", reading: "sama", options: ["様", "洋", "木", "羊"] },
    { id: 199, targetKanji: "球", meaning: "Koptok", reading: "kyuu", options: ["球", "玉", "王", "求"] },
    { id: 200, targetKanji: "発", meaning: "Jo'nash / Portlash", reading: "hatsu", options: ["発", "廃", "登", "道"] }
  ]
};